name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Change selon ta version

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Begin SonarCloud analysis
        run: |
          dotnet-sonarscanner begin `
            /k:"TON_PROJECT_KEY" `
            /o:"TON_ORG_KEY" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io"
        shell: pwsh

      - name: Build
        run: dotnet build --no-incremental

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:so
